site_name: Coronium ChatterBox
pages:
  - 'Introduction': 'index.md'
  - 'Server Install':
    - 'DigitalOcean': 'install/digitalocean.md'
    - 'Amazon EC2': 'install/ec2.md'
    - 'Quick Test': 'install/testing.md'
  - 'Server Guide':
    - 'Configuration': 'server/config.md'
    - 'Viewing Logs': 'server/logs.md'
    - 'Password': 'server/password.md'
    - 'System Service': 'server/system.md'
  - 'Client Guide':
    - 'Plugin': 'client/plugin.md'
    - 'Connecting': 'client/connect.md'
    - 'Overview': 'client/overview.md'
  - 'Client Events': 'events.md'
  - 'Client Actions': 'actions.md'
  - 'Development Tips': 'development.md'
  - 'Example Setup': 'example.md'
  - 'Demo': 'demo.md'
  - 'About': 'about.md'
copyright: "&copy;2017 C. Byerley - develephant.com"
theme: readthedocs
site_url: https://develephant.github.io/coronium-cs-docs
site_dir: ../docs
extra_css: 
  - css/code.css
markdown_extensions:
  - admonition
  - codehilite